version: '3'
services:
    mysql:
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_DATABASE=app
        
    app:
        build: ./
        restart: always
        depends_on:
            - mysql
        environment: 
            - BEHIND_PROXY=False
            - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:app@mysql:3306/app  # or sqlite:///../app.db
            - UPLOAD_PATH=/app/uploads
            - URL_PREFIX=  # keep it empty if you don't want to use it
            - LOGIN_PASSWORD=strong_password  # after fisrt start, you can delete this line
        ports:
            - "80:80" # or if you want to reverse proxy, change BEHIND_PROXY=False to BEHIND_PROXY=True, and using X-Real-IP to trasnfer IP 
